# Generated by Django 2.2.4 on 2019-12-16 12:40

from django.db import migrations

def fill_construction_year(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
            migrations.RunPython(fill_construction_year),
    ]
