# Generated by Django 2.2.4 on 2019-12-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20191216_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner',
            new_name='owner_depricated',
        ),
    ]
