# Generated by Django 2.2.4 on 2019-12-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20191216_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_depricated',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phone_pure',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
