# Generated by Django 2.2.4 on 2019-12-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20191218_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phone_pure',
            new_name='owner_phone_pure',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='owner_phonenumber',
        ),
    ]
